import { Component } from ".";

export default {
  title: "Components/Component",
  component: Component,
  tags: ["autodocs"],

  argTypes: {
    variant: {
      options: [
        "one-hundred-and-ninety-one",
        "twenty-five",
        "two-hundred-and-sixty-four",
        "one-hundred-and-four",
        "one-hundred-and-seventy-three",
        "one-hundred-and-seventy-one",
        "twelve",
        "sixty-seven",
        "two-hundred-and-forty-one",
        "one-hundred-and-seventy-two",
        "sixty-eight",
        "seventy-nine",
        "eighty-seven",
        "two-hundred-and-forty-three",
        "sixty-four",
        "one-hundred-and-eighty-five",
        "one-hundred-and-eighty",
        "one-hundred-and-eighty-nine",
        "one-hundred-and-eighty-seven",
        "two-hundred-and-ninety-nine",
        "one-hundred-and-fifty-six",
        "seventy-eight",
        "one-hundred-and-seventy-nine",
        "sixty-five",
        "one-hundred-and-seventy-four",
        "one",
        "eighty-four",
        "one-hundred-and-eighty-one",
        "one-hundred-and-eighty-four",
        "two-hundred-and-forty",
        "one-hundred-and-three",
        "one-hundred-and-sixty-nine",
        "one-hundred-and-eighty-three",
        "one-hundred-and-eighty-six",
        "two-hundred-and-sixty-three",
        "thirteen",
        "one-hundred-and-eighty-two",
        "two-hundred-and-nine",
        "one-hundred-and-fifty-five",
        "two-hundred-and-thirty-nine",
        "one-hundred-and-seventy-six",
        "one-hundred-and-seventy-seven",
        "two-hundred-and-ten",
        "one-hundred-and-eighty-eight",
        "three",
        "two-hundred-and-forty-five",
        "one-hundred-and-ninety-two",
        "two-hundred-and-forty-two",
        "one-hundred-and-sixty-eight",
        "twenty-six",
        "one-hundred-and-seventy-five",
        "two-hundred-and-forty-four",
        "seven",
        "one-hundred-and-ninety-three",
        "two-hundred-and-fifty",
        "eighty-two",
        "eighty-five",
        "two-hundred-and-ninety-eight",
        "eighty",
        "eighty-one",
        "two-hundred-and-forty-nine",
        "eleven",
        "one-hundred-and-seventy-eight",
        "eighty-six",
        "one-hundred-and-seventy",
        "eighty-three",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    text: "Blog",
    variant: "one-hundred-and-ninety-one",
    variantClassName: "",
    vectorClassName: "",
    vector: "/img/vector-21.svg",
    img: "/img/variant-12.svg",
    vector1: "/img/vector-22.svg",
    vectorClassNameOverride: "",
    vector2: "/img/vector-23.svg",
    imgClassName: "",
    vector3: "/img/vector-24.svg",
    imgClassNameOverride: "",
    vector4: "/img/vector-25.svg",
    vectorClassName1: "",
    vector5: "/img/vector-26.svg",
    vectorClassName2: "",
    vector6: "/img/vector-27.svg",
    vectorClassName3: "",
    vector7: "/img/vector-28.svg",
    vectorClassName4: "",
    vectorClassName5: "",
  },
};
